name: 生成签名并输出base64
on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: 配置JDK17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: 生成安卓密钥（单行无换行，避免语法报错）
        run: keytool -genkey -v -keystore my-key.jks -alias my-alias -keyalg RSA -keysize 2048 -validity 36500 -storepass 12345678 -keypass 12345678 -dname "CN=Dev,OU=Dev,O=Dev,L=City,ST=Province,C=CN"
          
      - name: 转换为base64文本
        run: base64 my-key.jks > key.txt
          
      - name: 输出base64字符串
        run: |
          echo "----------复制中间所有字符----------"
          cat key.txt
          echo "----------复制结束----------"
          
      - name: 备份下载密钥文件
        uses: actions/upload-artifact@v5
        with:
          name: my-key-jks备份
          path: my-key.jks
          retention-days: 7
